routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('products.index'));
});

Auth::routes();

Route::get('/home', 'ProductController@index')->name('home');
Route::delete('/carts/clear', 'CartController@clearCart')->name('carts.clear');
Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::resource('transactions','TransactionController');
Route::resource('carts','CartController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
   protected $fillable =['name'];

   public function products (){
    	return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Product;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $categories = Category::all();
        return view('categories.index')->with('categories',$categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'add-category' =>'required|unique:categories,name'
        ]);
        //taga save ng form
        $category = $request->input('add-category');
        $new_category = new Category;
        $new_category->name = $category;
        $new_category->save();

        //alert for front end
        $request->session()->flash('category_message','Category successfully added!');
        return redirect(route('categories.index')); 
     
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
         return view ('categories.create')->with('category',$category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' =>'required|unique:categories,name'
        ]);

        $category->update([
            'name' => $request->input('name')
        ]);

        $request->session()->flash('category_message','Category successfully updated!');

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect(route('categories.index'))->with('destroy_message','Category removed');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					Edit Category
				</h3>
				<hr>
				@if(Session::has('update_failed'))
					<div class="alert alert-warning">
						{{Session::get('update_failed')}}
					</div>
				@endif
				@if(Session::has('update_success'))
					<div class="alert alert-success">
						{{Session::get('update_success')}}
					</div>
				@endif
				<form method="post" action="{{route('categories.update',['category' =>$category->id])}}" enctype="multipart/form-data">
					@csrf
					@method('put')
					{{-- input for name --}}
					<div class="form-group">
						<label for="name">Product name:</label>
						<input 
							type="text" 
							name="name" 
							class="form-control" 
							id="name"
							value="{{$category->name}}" 
							>
					<button class="btn btn-dark w-100">Edit Item</button>
				</form>
			</div>
		</div>
	</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
	<div class="row">
		<div class="col-12 col-md-10 mx-auto">
			<h3 class="text-center">
				Categories
			</h3>
			@if(Session::has('category_message'))
			<div class="alert alert-success">
				{{Session::get('category_message')}}
			</div>
			@endif
			{{-- validation --}}
			@if($errors->has('add-category'))
			<div class="alert alert-danger">
				<small class="mb-0">Category not added
				</small>
			</div>
			@endif
			@if(Session::has('destroy_message'))
			<div class="alert alert-success text-center">
				{{Session::get('destroy_message')}}
			</div>
			@endif

			<div class="row">
				<table class="table table-striped">

					<tbody>



						@foreach($categories as $category)
						<tr>

							<td><a href="" >{{$category->name}}</a></td>
							<td>

								{{-- delete button --}}
								<form action="{{route('categories.destroy',['category'=>$category->id])}}" method="post">
									@csrf
									@method('DELETE')
									<button class="btn btn-secondary w-10 my-1 float-right">Delete</button>
								</form>

								<a href="{{route('categories.edit',['category'=>$category->id])}}" 
									class="w-10 btn btn-primary my-1 mr-1 float-right">
									Edit
								</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>

				

				
			</div>
		</div>

		<div class="col-12 col-md-2 mx-auto">
			<h3 class="text-center">
				New Category
			</h3>
			<hr>
			{{-- alert message --}}


			<form method="post" action="{{route('categories.store')}}" enctype="multipart/form-data">
				@csrf
				<div class="form-group">
					<label for="add-category">
						Add category:	
					</label>
					<input type="text" name="add-category" id="add-category" class="form-control">
				</div>

				<button class="btn btn-outline-secondary w-100">Add category</button>

			</form>
		</div>
	</div>
</div>
@endsection