routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('products.index'));
});

Auth::routes();

Route::get('/home', 'ProductController@index')->name('home');
Route::delete('/carts/clear', 'CartController@clearCart')->name('carts.clear');
Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::resource('transactions','TransactionController');
Route::resource('carts','CartController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
	use SoftDeletes;
	
    public function category (){
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Category;
use Str;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index')->with('products',$products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        
        $this->authorize('isAdmin');
        $categories = Category::all();
        return view('products.create')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->authorize('create',$product);

        $request->validate([
                'name' => 'required|string',
                'category' => 'required|string|unique:categories,name',
                'image' => 'required|image', //3000kilobytes
                'description'=> 'required|string',
                'serial'=>'required|numeric'
            ]);

        // for image

        $file = $request->file('image');
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $file_extension = $file->extension();
        $random_chars = Str::random(10);
        $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;
        $filepath = $file->storeAs('images', $new_file_name, 'public');

        // get input value from store

        $name = $request->input('name');
        $category_id = $request->input('category');
        $description = $request->input('description');
        $serial_number = $request->input('serial');
        


        $product = new Product;
        $product->name = $name;
        $product->serial_number = $serial_number;
        $product->category_id = $category_id;
        $product->description = $description;
        $product->image = $filepath;
        $product->save();

        return redirect(route('products.index', ['product' => $product->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show')->with('product',$product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $this->authorize('update',$product);
        $categories = Category::all();
        return view('products.edit')
            ->with('product',$product)
            ->with('categories',$categories)
            ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
                'name' => 'required|string',
                'category' => 'required|string|unique:categories,name',
                'image' => 'required|image', 
                'description'=> 'required|string',
                'serial'=>'required|numeric'
            ]);

        if(
            !$request->hasFile('image') &&
            $product->name == $request->input('name') &&
            $product->description == $request->input('description') &&
            $product->serial_number == $request->input('serial') &&
            $product->category_id == $request->input('category') 
        ){      
            $request->session()->flash('update_failed','Something went wrong');      
            
        } else {

            if($request->hasFile('image')){
                $request->validate([
                    'image' => 'required|image'
                ]);
            $file = $request->file('image'); 
            $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $file_extension = $file->extension();
            $random_chars = Str::random(10);
            $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;
            $filepath = $file->storeAs('images', $new_file_name, 'public');
            $product->image=$filepath;
            }

            $product->name = $request->input('name');
            $product->description = $request->input('description');
            $product->serial_number == $request->input('serial');
            $product->category_id = $request->input('category');
            $product->save();

            $request->session()->flash('update_success','Product is successfully updated');

        }   

        return redirect (route('products.edit',['product'=>$product->id]));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        // $this->authorize('delete',$product);
        $product->delete();
        return redirect(route('products.index'))->with('destroy_message','Equipment removed');
    }

        
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					Add Golf Equipment
				</h3>
				<hr>
				<form method="post" action="{{route('products.store')}}" enctype="multipart/form-data">
					@csrf

					{{-- input for name --}}
					<div class="form-group">
						<label for="name">Golf Equipment name:</label>
						<input 
							type="text" 
							name="name" 
							class="form-control" 
							id="name"
							>
					</div>
						{{-- validation --}}
						@if($errors->has('name'))
							<div class="alert alert-danger">
								<small class="mb-0">Equipment name required</small>
							</div>
						@endif
					
					{{-- input for category --}}
					<div class="form-group">
					    <label for="category">Golf Equipment Category</label>
					    <select class="form-control" id="category" name="category">
					      @foreach($categories as $category)
					      	<option value="{{$category->id}}">{{$category->name}}</option>
					      @endforeach	
					    </select>
					</div>
						{{-- validation --}}
						@if($errors->has('category'))
							<div class="alert alert-danger">
								<small class="mb-0">Equipment category required</small>
							</div>
						@endif

					{{-- input for image --}}
					<div class="form-group">
						<label for="image">Equipment image:</label>
						<input 
							type="file" 
							name="image" 
							class="form-control-file" 
							id="image"
							>
					</div>		
						{{-- validation --}}
						@if($errors->has('image'))
							<div class="alert alert-danger">
								<small class="mb-0">Equipment image required. Check if image is not greater than 3mb.</small>
							</div>
						@endif			
					{{-- input for description --}}
					<div class="form-group">
						<label for="description">Equipment description:</label>
						<textarea 
							id="description" 
							class="form-control" 
							cols="30" 
							rows="10" 
							name="description"
						></textarea>
					</div>
						{{-- validation --}}
						@if($errors->has('description'))
							<div class="alert alert-danger">
								<small class="mb-0">Product description required</small>
							</div>
						@endif

					

					{{-- input for serial number --}}
					<div class="form-group">
						<label for="quantity">Serial Number:</label>
						<input 
							type="number"
							id="serial" 
							class="form-control" 
							name="serial"
						>
					</div>

					<button class="btn btn-dark w-100">Add Item</button>



				</form>
			</div> {{-- end of add product form --}}
			{{-- column for add category form --}}

			<div class="col-12 col-md-2 mx-auto">
				<h3 class="text-center">
					New Category
				</h3>
				<hr>
				{{-- alert message --}}
				@if(Session::has('category_message'))
				<div class="alert alert-success">
					{{Session::get('category_message')}}
				</div>
				@endif
				{{-- validation --}}
				@if($errors->has('add-category'))
					<div class="alert alert-danger">
						<small class="mb-0">Category not added
						</small>
					</div>
				@endif

				<form method="post" action="{{route('categories.store')}}" enctype="multipart/form-data">
					@csrf
					<div class="form-group">
						<label for="add-category">
						Add category:	
						</label>
						<input type="text" name="add-category" id="add-category" class="form-control">
					</div>

					<button class="btn btn-secondary w-100">Add category</button>
					
				</form>
			</div>
		</div>
	</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					Edit Equipment
				</h3>
				<hr>
				@if(Session::has('update_failed'))
					<div class="alert alert-warning">
						{{Session::get('update_failed')}}
					</div>
				@endif
				@if(Session::has('update_success'))
					<div class="alert alert-success">
						{{Session::get('update_success')}}
					</div>
				@endif
				<form method="post" action="{{route('products.update',['product' =>$product->id])}}" enctype="multipart/form-data">
					@csrf
					@method('PUT')
					{{-- input for name --}}
					<div class="form-group">
						<label for="name">Equipment name:</label>
						<input 
							type="text" 
							name="name" 
							class="form-control" 
							id="name"
							value="{{$product->name}}" 
							>
					</div>
						{{-- validation --}}
						@if($errors->has('name'))
							<div class="alert alert-danger">
								<small class="mb-0">Product name required</small>
							</div>
						@endif

					{{-- input for category --}}
					<div class="form-group">
					    <label for="category">Product category</label>
					    <select class="form-control" id="category" name="category">
					      @foreach($categories as $category)
					      	<option 
					      		value="{{$category->id}} 
					      		"
					      		@if($product->category_id == $category->id) 
					      		selected
					      		@endif
					      		>
					      			{{$category->name}}
					      		</option>
					      @endforeach	
					    </select>
					</div>
						{{-- validation --}}
						@if($errors->has('category'))
							<div class="alert alert-danger">
								<small class="mb-0">Product category required</small>
							</div>
						@endif

					{{-- input for image --}}
					<div class="form-group">
						<label for="image">Product image:</label>
						<input 
							type="file" 
							name="image" 
							class="form-control-file" 
							id="image"
							>
					</div>		
						{{-- validation --}}
						@if($errors->has('image'))
							<div class="alert alert-danger">
								<small class="mb-0">Product image required.</small>
							</div>
						@endif		


					{{-- input for description --}}
					<div class="form-group">
						<label for="description">Product description:</label>
						<textarea 
							id="description" 
							class="form-control" 
							cols="30" 
							rows="10" 
							name="description"
						>{{$product->description}}</textarea>
					</div>
						{{-- validation --}}
						@if($errors->has('description'))
							<div class="alert alert-danger">
								<small class="mb-0">Product description required</small>
							</div>
						@endif

					
						{{-- validation --}}
						@if($errors->has('quantity'))
							<div class="alert alert-danger">
								<small class="mb-0">{{$errors->first('quantity')}}</small>
							</div>
						@endif

					{{-- input for serial number --}}
					<div class="form-group">
						<label for="price">Serial Number:</label>
						<input 
							type="number" 
							name="serial" 
							class="form-control" 
							id="serial"
							value="{{$product->serial_number}}" 
							>
					</div>
						{{-- validation --}}
						@if($errors->has('serial'))
							<div class="alert alert-danger">
								<small class="mb-0">{{$errors->first('serial')}}</small>
							</div>
						@endif
					
	

					<button class="btn btn-dark w-100">Edit Item</button>



				</form>
			</div>
		</div>
	</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')



	{{-- @if(Session::has('destroy_message'))
		<div class="alert alert-success text-center">
			{{Session::get('destroy_message')}}
		</div>
		@endif --}}

		<div class="jumbotron" id="jumbo">
			<h1 id="tag" class="jumbotxt display-4 text-right">Golf Equipment Rental for the Travelling Golfer</h1>
			<p class="jumbotxt lead text-right"><em>Rent the latest golf equipments from leading golf brands</em></p>
		</div>

		<div class="container">

			<div class="row ">
				<div class="col-12 col-md-10 mx-auto">
					<div class="row">
						@foreach($products as $product)
						<div class="col-12 col-md-4 col-lg-3  mb-3">
							
							<div class="card">
								<div class="card-body text-center">
									<img src="{{url('/public/'.$product->image)}}" class="img-fluid card-img-top">
									<h2 class="card-title">
										{{$product->name}}
									</h2>

									<p class="card-text">
										{{$product->description}}
									</p>
									<p class="card-text">
										{{$product->status}}
									</p>
									@cannot('isAdmin')	
									<form action="{{route('carts.store')}}" method="post" class="add-to-cart-field text-center">
										@csrf
										<div class="form-group">
											<input type="hidden" name="id" value="{{$product->id}}">
										</div>
										<button	class="btn btn-success w-85">
											Add to Cart
										</button>
									</form>
									@endcannot

									@can('isAdmin')
									<a href="{{route('products.edit',['product'=>$product->id])}}" class="btn btn-warning btn-block mb-1 ">
										Edit 
									</a>

									{{-- delete button --}}
									<form action="{{route('products.destroy',$product->id)}}" method="post">
										@csrf
										@method('DELETE')
										<button class="btn btn-danger btn-block">Delete </button>
									</form>
									@endcan
								</div>
							</div>
						</div>
						@endforeach	
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					View Golf Equipments
				</h3>
				<hr>
				<div class="card">
						<div class="card-body">
							<img src="{{url('/public/'.$product->image)}}" class="card-img-top">
							<h2 class="card-title">
								{{$product->name}}
							</h2>
							<p class="card-text">
								<strong>
									&#8369; {{$product->serial_number}}
								</strong>
							</p>
							<p class="card-text">
								{{$product->description}}
							</p>
							<p class="card-text">
								{{$product->quantity}}
							</p>
						</div>
						<div class="card-foot">
							{{-- add to cart button --}} 
							@cannot('isAdmin')
{{-- 							<a 
								href="#" 
								class="btn btn-success w-100 my-1"
								>
								Add to Cart
							</a> --}}
							<form action="{{route('carts.store')}}" method="post" class="add-to-cart-field">
									<div class="form-group">
										@csrf
										<input type="hidden" name="id" value="{{$product->id}}">
										<label for="quantity">Quantity:</label>
										{{-- start of append button --}}
										<div class="input-group mb-3">
											  <div class="input-group-prepend">
											    <button class="btn btn-outline-secondary deduct-quantity" type="button" data-id="{{$product->id}}">-</button>
											  </div>
											  
											  <input type="text" name="quantity" class="form-control input-quantity" data-id="{{$product->id}}">

											  <div class="input-group-append">
    											<button class="btn btn-outline-secondary add-quantity " type="button" data-id="{{$product->id}}">+</button>
  											  </div>
										</div>
										{{-- end of append button --}}
									</div>
								<button 
									
									type="submit" 
									class="btn btn-success w-100 my-1"
									>
									Add to Cart
								</button>
								</form>
							@endcannot
							@can('isAdmin')
							{{-- view button --}}
{{-- 							<a 
								href="{{route('products.show',['product' =>$product->id])}}" 
								class="btn btn-primary w-100 my-1"
								>
								View Product
							</a> --}}
							<a 
								href="{{route('products.index')}}" 
								class="btn btn-primary w-100 my-1"
								>
								Back to Products
							</a>
							{{-- edit button --}}
							<a 
								href="{{route('products.edit',['product'=>$product->id])}}" 
								class="w-100 btn btn-warning my-1"
								>
								Edit Product
							</a>
							{{-- delete button --}}
							<form action="{{route('products.destroy',['product'=>$product->id])}}" method="post">
								@csrf
								@method('DELETE')
								<button class="btn btn-danger w-100 my-1">Delete Product</button>
							</form>
							@endcan
						</div>
				</div>
			</div>
		</div>

	</div>
@endsection